
export const FETCH_START = 'FETCH_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL'
export const GET_GEOLOCATION = 'GET_GEOLOCATION';
export const GEOLOCATION_DENIED = 'GEOLOCATION_DENIED';

export const FETCH_DUST_SUCCESS = 'FETCH_DUST_SUCCESS';
export const FETCH_DUST_FAIL = 'FETCH_DUST_FAIL'